#!/bin/bash
#chkconfig: 2345 80 90
#description:auto_run

SERVERNAME="qttroom"

start()
{
    echo "start $SERVERNAME"
    nohup $HOME\/$SERVERNAME -c /etc/qttserver.config & 
    echo "start $SERVERNAME ok!"
    exit 0;
}
 
stop()
{
    echo "stop $SERVERNAME"
    pkill $SERVERNAME
    echo "stop $SERVERNAME ok!"
}
 
case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
*)
    echo "usage: $0 start|stop|restart"
    exit 0;
esac
exit
