#!/bin/bash
#chkconfig: 2345 80 90
#description:auto_run

EXECUTOR="qttroom"

start()
{
    echo "start $EXECUTOR"
    nohup $HOME\/$EXECUTOR -c /etc/qttserver.config & 
    echo "start $EXECUTOR ok!"
    exit 0;
}
 
stop()
{
    echo "stop $EXECUTOR"
    pkill $EXECUTOR
    echo "stop $EXECUTOR ok!"
}
 
case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
*)
    echo "usage: $0 start|stop|restart"
    exit 0;
esac
exit
